### ISSUE TITLE
Meeting Notes: March 10 , 2022

### ISSUE THREAD

**Issue by isabela-pf** [isabela-pf/internship#13]
# Meeting topics:
## Follow-up on last week's to-dos
- Continue making outline of report
   - [Figma files of the 5 outlines](https://www.figma.com/file/FvWBXRoJzuBZmYfheD2cZS?embed_host=share&kind=&node-id=0%3A1&viewer=1)
- Ask for feedback on outline from
   - Isabela, Mars, Tony Fast, Gabriel Fouasnon
- Continue creating User Journey diagrams
## Discussion topics and Resources
- Some uncertainty how and when to schedule feedback sessions
## Potential to-do items
- Let's sort out scheduling with supporters!

## Scheduling next meeting
- Will anyone be out of office in the next week? Any other scheduling conflicts?
## Other
- Time for any learning/larger discussion (time permitting)
- Anything else?

**Comment by MarsBarLee** [comment]
Consolidating messages we did about scheduling audits and calls

## Accessibility channel
### Isabela's message: 
For those of you that might not know, our design intern [@swast](https://quansight.slack.com/team/U02UKUYQ4E9) is researching accessibility issues with collaborative documents (mainly web-based, but open to others)! As she's gotten acquainted with the topic, we'd like to make some time for her to collaborate with other people interested in accessibility at Quansight. There's a few ways you could join in
Meet with [@swast](https://quansight.slack.com/team/U02UKUYQ4E9) and use a screen reader and/or keyboard-only navigation work with her in a collaborative document (bonus points if you are using a screen reader that isn't Apple's built-in VoiceOver). This will help her better test how other applications currently work, and give you a chance to explore what accessibility is like in different applications.
Give feedback on what kind of information you'd find most helpful in a best practices-style document about real time collaboration and accessibility UX. For example, would you want information on a specific use case, want concrete examples included, so on. This could be through a meeting, on slack asynchronously, or something else.
Reach out with another idea! There's still time to explore and you all have lots of experience we'd like to incorporate if you are interested.
If you have any questions, you can post in a thread on this message or reach out to [@swast](https://quansight.slack.com/team/U02UKUYQ4E9), [@Mars Lee](https://quansight.slack.com/team/US75A0WP4), and [@Isabela](https://quansight.slack.com/team/U013012ARH7). Thanks!

### Interested parties
Eric Charles: Happy to join a call and experiment with you via **screen reader**
Noa: Happy to chat about my experience using the Browser Extension from **Wave Evaluation Tool** for small websites. I’m no expert, but I found it helpful in a few use cases so far.
Tony: we can **rtc in jupyter/jits**i; i think i still have some working binders. rtc with video in the same tab is a really cool elevated collaborative state 
Gabriel: I have a **windows machine with Nvda** installed

**Comment by MarsBarLee** [comment]
Oops, didn't mean to keep the Slack links, I'll remove them.

**Comment by MarsBarLee** [comment]
[Figma files of the 5 outlines](https://www.figma.com/file/FvWBXRoJzuBZmYfheD2cZS?embed_host=share&kind=&node-id=0%3A1&viewer=1)

**Comment by isabela-pf** [comment]
About recommendations:
- Can also include ideas that we haven't been able to test (maybe labelled in a different header)
- We can have a section with questions we still have?
- Can be based on reflection on other research
